### ISSUE TITLE
Error record database

### ISSUE THREAD

**Issue by AndreaOliveira** [leorenis/icontent#6]
**I used the configuration moodle debug developer, and:**
ps.: Please, if I used the wrong way, tell me.

Debug info: SQLState: 42S22<br>
Error Code: 207<br>
Message: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'NAME'.<br>

SELECT pq.id AS qpid, 
q.id AS qid, 
q.NAME, 
q.questiontext, 
q.questiontextformat, 
q.qtype 
FROM mdl_icontent_pages_questions pq 
INNER JOIN mdl_question q 
ON pq.questionid = q.id 
WHERE pq.pageid = '2' 
AND pq.cmid = '42';
[array (
0 => '2',
1 => '42',
)] 
Error code: dmlreadexception

---

Stack trace:
line 474 of \lib\dml\moodle_database.php: dml_read_exception thrown
line 291 of \lib\dml\sqlsrv_native_moodle_database.php: call to moodle_database->query_end()
line 398 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->query_end()
line 859 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->do_query()
line 907 of \lib\dml\sqlsrv_native_moodle_database.php: call to sqlsrv_native_moodle_database->get_recordset_sql()
line 1221 of \mod\icontent\locallib.php: call to sqlsrv_native_moodle_database->get_records_sql()
line 1723 of \mod\icontent\locallib.php: call to icontent_get_pagequestions()
line 2368 of \mod\icontent\locallib.php: call to icontent_make_questionsarea()
line 88 of \mod\icontent\view.php: call to icontent_get_fullpageicontent()

**Comment by leorenis** [comment]
Andreia fiz uma atualização para solucionar essa questão! Por favor, atualize o arquivo locallib.php do plugin iContent no seu ambiente. Se funcionar corretamente, lanço uma nova versão no diretório de plugin do moodle. Senão, continuo as correções. 

Obrigado!

EN
Andreia made an update to resolve this issue! Please update the locallib.php file iContent plugin in your environment. If it works correctly, throw a new version on Moodle plugin directory. Otherwise, keep the corrections.

Thank you!
